Imports

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

# display settings
pd.set_option("display.max_columns", None)

# plotting style
sns.set_style("whitegrid")

print("Libraries loaded successfully")

Libraries loaded successfully

Load Dataset

In [54]:
data_path = Path("../data/MachineLearningRating_v3.txt")

df = pd.read_csv(data_path, delimiter="|")

df.head()

/var/folders/td/g0nj9lw14y165dmqgtz9jxzh0000gn/T/ipykernel_55437/164759178.py:3: DtypeWarning: Columns (0: CapitalOutstanding, 1: CrossBorder) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_path, delimiter="|")

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,MaritalStatus,Gender,Country,Province,PostalCode,MainCrestaZone,SubCrestaZone,ItemType,mmcode,VehicleType,RegistrationYear,make,Model,Cylinders,cubiccapacity,kilowatts,bodytype,NumberOfDoors,VehicleIntroDate,CustomValueEstimate,AlarmImmobiliser,TrackingDevice,CapitalOutstanding,NewVehicle,WrittenOff,Rebuilt,Converted,CrossBorder,NumberOfVehiclesInFleet,SumInsured,TermFrequency,CalculatedPremiumPerTerm,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,0.01,Monthly,25.0000,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,0.01,Monthly,25.0000,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,0.01,Monthly,25.0000,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,119300.00,Monthly,584.6468,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,119300.00,Monthly,584.6468,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [55]:
print("Shape:", df.shape)

Shape: (1000098, 52)

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000098 entries, 0 to 1000097
Data columns (total 52 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   UnderwrittenCoverID       1000098 non-null  int64
 1   PolicyID                  1000098 non-null  int64
 2   TransactionMonth          1000098 non-null  str
 3   IsVATRegistered           1000098 non-null  bool
 4   Citizenship               1000098 non-null  str
 5   LegalType                 1000098 non-null  str
 6   Title                     1000098 non-null  str
 7   Language                  1000098 non-null  str
 8   Bank                      854137 non-null   str
 9   AccountType               959866 non-null   str
 10  MaritalStatus             991839 non-null   str
 11  Gender                    990562 non-null   str
 12  Country                   1000098 non-null  str
 13  Province                  1000098 non-null  str
 14  PostalCode                1000098 non-null  int64
 15  MainCrestaZone            1000098 non-null  str
 16  SubCrestaZone             1000098 non-null  str
 17  ItemType                  1000098 non-null  str
 18  mmcode                    999546 non-null   float64
 19  VehicleType               999546 non-null   str
 20  RegistrationYear          1000098 non-null  int64
 21  make                      999546 non-null   str
 22  Model                     999546 non-null   str
 23  Cylinders                 999546 non-null   float64
 24  cubiccapacity             999546 non-null   float64
 25  kilowatts                 999546 non-null   float64
 26  bodytype                  999546 non-null   str
 27  NumberOfDoors             999546 non-null   float64
 28  VehicleIntroDate          999546 non-null   str
 29  CustomValueEstimate       220456 non-null   float64
 30  AlarmImmobiliser          1000098 non-null  str
 31  TrackingDevice            1000098 non-null  str
 32  CapitalOutstanding        1000096 non-null  object
 33  NewVehicle                846803 non-null   str
 34  WrittenOff                358197 non-null   str
 35  Rebuilt                   358197 non-null   str
 36  Converted                 358197 non-null   str
 37  CrossBorder               698 non-null      str
 38  NumberOfVehiclesInFleet   0 non-null        float64
 39  SumInsured                1000098 non-null  float64
 40  TermFrequency             1000098 non-null  str
 41  CalculatedPremiumPerTerm  1000098 non-null  float64
 42  ExcessSelected            1000098 non-null  str
 43  CoverCategory             1000098 non-null  str
 44  CoverType                 1000098 non-null  str
 45  CoverGroup                1000098 non-null  str
 46  Section                   1000098 non-null  str
 47  Product                   1000098 non-null  str
 48  StatutoryClass            1000098 non-null  str
 49  StatutoryRiskType         1000098 non-null  str
 50  TotalPremium              1000098 non-null  float64
 51  TotalClaims               1000098 non-null  float64
dtypes: bool(1), float64(11), int64(4), object(1), str(35)
memory usage: 769.5+ MB

In [57]:
df.shape

(1000098, 52)

In [58]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
UnderwrittenCoverID,1000098.0,1.048175e+05,6.329371e+04,1.000000e+00,5.514300e+04,9.408300e+04,1.391900e+05,3.011750e+05
PolicyID,1000098.0,7.956682e+03,5.290039e+03,1.400000e+01,4.500000e+03,7.071000e+03,1.107700e+04,2.324600e+04
PostalCode,1000098.0,3.020601e+03,2.649854e+03,1.000000e+00,8.270000e+02,2.000000e+03,4.180000e+03,9.870000e+03
mmcode,999546.0,5.487770e+07,1.360381e+07,4.041200e+06,6.005692e+07,6.005842e+07,6.005842e+07,6.506535e+07
RegistrationYear,1000098.0,2.010225e+03,3.261391e+00,1.987000e+03,2.008000e+03,2.011000e+03,2.013000e+03,2.015000e+03
Cylinders,999546.0,4.046642e+00,2.940201e-01,0.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,1.000000e+01
cubiccapacity,999546.0,2.466743e+03,4.428006e+02,0.000000e+00,2.237000e+03,2.694000e+03,2.694000e+03,1.288000e+04
kilowatts,999546.0,9.720792e+01,1.939326e+01,0.000000e+00,7.500000e+01,1.110000e+02,1.110000e+02,3.090000e+02
NumberOfDoors,999546.0,4.019250e+00,4.683144e-01,0.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,6.000000e+00
CustomValueEstimate,220456.0,2.255311e+05,5.645157e+05,2.000000e+04,1.350000e+05,2.200000e+05,2.800000e+05,2.655000e+07
NumberOfVehiclesInFleet,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SumInsured,1000098.0,6.041727e+05,1.508332e+06,1.000000e-02,5.000000e+03,7.500000e+03,2.500000e+05,1.263620e+07
CalculatedPremiumPerTerm,1000098.0,1.178757e+02,3.997017e+02,0.000000e+00,3.224800e+00,8.436900e+00,9.000000e+01,7.442217e+04
TotalPremium,1000098.0,6.190550e+01,2.302845e+02,-7.825768e+02,0.000000e+00,2.178333e+00,2.192982e+01,6.528260e+04
TotalClaims,1000098.0,6.486119e+01,2.384075e+03,-1.200241e+04,0.000000e+00,0.000000e+00,0.000000e+00,3.930921e+05

In [69]:
missing_values = df.isnull().sum()

missing_values[missing_values > 0].sort_values(ascending=False)

CustomValueEstimate    779642
Converted              641901
Rebuilt                641901
WrittenOff             641901
LossRatio              381922
NewVehicle             153295
Bank                   145961
AccountType             40232
Gender                   9536
MaritalStatus            8259
Model                     552
Cylinders                 552
cubiccapacity             552
bodytype                  552
NumberOfDoors             552
VehicleIntroDate          552
make                      552
VehicleType               552
mmcode                    552
kilowatts                 552
CapitalOutstanding          2
dtype: int64

In [86]:
df["LossRatio"] = np.where(
    df["TotalPremium"] > 0,
    df["TotalClaims"] / df["TotalPremium"],
    0
)

df["Margin"] = df["TotalPremium"] - df["TotalClaims"]

In [88]:
df["Margin"] = df["TotalPremium"] - df["TotalClaims"]

In [91]:
df[["LossRatio", "Margin"]].describe()

          LossRatio        Margin
count  1.000098e+06  1.000098e+06
mean   2.163699e-01 -2.955694e+00
std    7.304735e+00  2.367137e+03
min   -1.870012e+01 -3.928486e+05
25%    0.000000e+00  0.000000e+00
50%    0.000000e+00  2.157687e+00
75%    0.000000e+00  2.192982e+01
max    2.553600e+03  6.528260e+04

In [92]:
df[["LossRatio", "Margin"]].describe()
df.isnull().sum().sort_values(ascending=False)
df.shape
df.duplicated().sum()

np.int64(0)

In [70]:
df["CapitalOutstanding"] = pd.to_numeric(df["CapitalOutstanding"], errors="coerce")

In [71]:
df["Cylinders"] = df["Cylinders"].replace(0, np.nan)
df["Cylinders"] = df["Cylinders"].fillna(df["Cylinders"].median())

In [72]:
df["cubiccapacity"] = df["cubiccapacity"].fillna(df["cubiccapacity"].median())
df["kilowatts"] = df["kilowatts"].fillna(df["kilowatts"].median())
df["NumberOfDoors"] = df["NumberOfDoors"].fillna(df["NumberOfDoors"].median())

In [73]:
cat_cols = ["VehicleType","make","Model","bodytype","VehicleIntroDate","mmcode"]

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [74]:
df["Bank"] = df["Bank"].fillna("Unknown")
df["AccountType"] = df["AccountType"].fillna("Unknown")

df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])
df["MaritalStatus"] = df["MaritalStatus"].fillna(df["MaritalStatus"].mode()[0])

In [75]:
flag_cols = ["Converted","Rebuilt","WrittenOff","NewVehicle"]
df[flag_cols] = df[flag_cols].fillna("Unknown")

In [76]:
df["CustomValueEstimate_missing"] = df["CustomValueEstimate"].isnull().astype(int)

df["CustomValueEstimate"] = df["CustomValueEstimate"].fillna(
    df["CustomValueEstimate"].median()
)

In [ ]:
df.isnull().sum().sort_values(ascending=False)
df.duplicated().sum()
df.shape

(1000098, 52)

No infinite values

In [78]:
np.isinf(df.select_dtypes(include=[np.number])).sum()

UnderwrittenCoverID            0
PolicyID                       0
PostalCode                     0
mmcode                         0
RegistrationYear               0
Cylinders                      0
cubiccapacity                  0
kilowatts                      0
NumberOfDoors                  0
CustomValueEstimate            0
CapitalOutstanding             0
SumInsured                     0
CalculatedPremiumPerTerm       0
TotalPremium                   0
TotalClaims                    0
LossRatio                      0
CustomValueEstimate_missing    0
dtype: int64

In [82]:
df["Margin"] = df["TotalPremium"] - df["TotalClaims"]

In [84]:
"LossRatio" in df.columns

True